language: php

php:
  - 5.3
  - 5.5
  # @TODO test 5.6 when we move to 5.5
  #- 5.6

cache:
  bundler: true
  apt: true

env:
  - COMPOSER_BIN_DIR=$TRAVIS_BUILD_DIR/build/bin BEHAT_PARAMS='{"extensions":{"Behat\\MinkExtension":{"base_url":"http://localhost/"}}}'

addons:
  artifacts:
    paths:
    - $TRAVIS_BUILD_DIR/build/phing/screenshot-fail.png

notifications:
  email:
  - adam.malone@acquia.com
  - james.gollan@acquia.com
  - paul.killer@gmail.com
  - sean.hamlin@acquia.com
  - stuart.rowlands@acquia.com
  slack:
    secure: X8EweDK9bHjnt+IOy3XUWu18gRQ8usBHBOtTiZmhBja2ooPzfGj7QnK7BcM/5bgnyJctOZ0vlJMw38e8mnj4d6eWGCd+2zM56mHK1aIBoW7nXl/rAVVuBjfbN3+V67M9JgPnXCwcjxhsanlXNdprPgJ+fwetTJldqqlptdOFoZ8zEZ2piS2IDPyrQqcKhPVH2fWb116LxC/stMsK8vDsIfy+eRmiuQT7xZj+h1/cbAkUled2DYpPdHaJdkV/sQrJWUqCkH7xBO9GTVyYZwA5fzJPnBQZD6MGEK/lNgc2f93aOtrr9a21BEq2zS6jSxP1jeslEXqPLV5SFEWA+t8f59dfyggeFbxTIfrHohX0iJVjPAlWl1c8FkklYWxYmqPB1uRFIJkSPsF3ZQPXdBMbOItAMnDGYyit+oBowFZNoq213vkqBO2bgr98jdfVBMrVbZt2r/hpeEbLh0ckycrcFEXvLW2tq6EdScCwNNtIemWWjcpgoBQ+rno0Sz45rIrkOsVxtKK7aVHCrJ8+jQBvVoZeGmB2kQxmKmukDNNCG3zIZlcX+ukR60mH7Z1OifmSnlsez1hkq/Pvb79Bry7lsIkjZVrD9FwkfZqhlNCG162P3/ZPt1pxDTMeLm9nOo7nkLPFgoszE1jh/WTA8CnsXRUXIBPq+wHw/wZBoVFYEqU=

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq postfix
  - composer selfupdate

install:
  - composer install --working-dir=build --prefer-source
  - export PATH=$PATH:$TRAVIS_BUILD_DIR/build/bin

before_script:
  # Create a mock mail system so Drupal install can send email somewhere.
  - sudo service postfix stop
  - smtp-sink -d "%d.%H.%M.%S" localhost:2500 1000 &
  - echo -e '#!/usr/bin/env bash\nexit 0' | sudo tee /usr/sbin/sendmail
  - echo 'sendmail_path = "/usr/sbin/sendmail -t -i "' | sudo tee "/home/travis/.phpenv/versions/`php -r 'echo PHP_VERSION;'`/etc/php.ini"

  # Install Apache
  - sudo apt-get install -y apache2 libapache2-mod-fastcgi
  - sudo cp ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf.default ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf
  - sudo a2enmod rewrite actions fastcgi alias
  - echo "cgi.fix_pathinfo = 1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - ~/.phpenv/versions/$(phpenv version-name)/sbin/php-fpm
  - sudo cp -f build/travis/travis-ci-apache /etc/apache2/sites-available/default
  - sudo sed -e "s?%TRAVIS_BUILD_DIR%?$(pwd)?g" --in-place /etc/apache2/sites-available/default
  - sudo service apache2 restart

  # Create Database
  - mysql -e 'CREATE DATABASE travis_ci_govcms_drupal;'

  # Build the codebase
  - phing -f build/phing/build.xml build:local

script:
  # Run tests
  - phing -f build/phing/build.xml run-tests

after_success:
  - phing -f build/phing/build.xml post-commit

